plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'depth.main'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Web / Security
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	// Swagger(OpenAPI)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.4'

	// JPA / Validation / DB Driver
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.postgresql:postgresql:42.7.8'
	runtimeOnly   'com.mysql:mysql-connector-j'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// External API / AWS
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'

	// Mail / SMS
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'net.nurigo:sdk:4.3.0'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly   'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly   'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// Lombok
	compileOnly         'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly    'org.junit.platform:junit-platform-launcher'

	// google sheet api
	implementation 'com.google.api-client:google-api-client:2.2.0'
	implementation 'com.google.apis:google-api-services-sheets:v4-rev20220927-2.0.0'
	implementation 'com.google.auth:google-auth-library-oauth2-http:1.16.0'
	implementation 'com.google.http-client:google-http-client-gson:1.43.3'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.1"
		mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:3.4.2"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
