# 민감한 API 키 정보

external-api:
  nts-business:
    key: "31c27089b5ad9c834ed666dee3678f768ca7af88c38dfae2f1ab33f80998acac"

email:
  username: "ljs08010@gmail.com"
  password: "urxbkesdelxtiyty"

coolsms:
  sms:
    accessKey: "NCSYISO6C2MMSWIC"
    secretKey: "ODGKX0NKSENXFIOSBZH1I6HKRARRHHG5"
    senderPhoneNumber: "01074008952"

kakao:
  rest-api-key: "4ffe4ece82e9a8179f55d525d645bb58"

google:
  places:
    api-key: "AIzaSyC2lYLiIwSi6en9jCGh_SU3WIeHQOpooEM"