spring:
  profiles:
    active: local
    include: secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      region:
        static: ap-seoul-1

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    filter: true
    operations-sorter: method
    display-request-duration: true
    supported-submit-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE" ]
    tags-sorter: alpha

email:
  host: smtp.gmail.com
  port: 587
  verification:
    expiry-time: 10

coolsms:
  sms:
    apiUrl: "https://api.coolsms.co.kr"
  verification:
    expiry-time: 5

kakao:
  local:
    base-url: "https://dapi.kakao.com"

google:
  places:
    base-url: "https://places.googleapis.com"

jwt:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 1209600